version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo In the pre_build phase...
  build:
    commands:
      - echo Build completed on `date`
      - gradle build -x test
  post_build:
    commands:
      - echo Build completed on `data`
artifacts:
  files:
    - build/libs/*.jar
  discard-paths: yes
